# 二.OpenCV+Numpy库读取与修改像素

主要讲解 OpenCV+Numpy 图像处理基础知识，包括读取像素和修改像素。知识点如下：

1.传统读取像素方法

2.传统修改像素方法

3.Numpy读取像素方法

4.Numpy修改像素方法

## 2.1传统读取像素方法

1.灰度图像，返回灰度值
返回值=图像(位置参数)，
例：p = img[88,142]


In [ ]:
# -*- coding:utf-8 -*-
import cv2

#读取图片
img = cv2.imread("test.jpg", cv2.IMREAD_UNCHANGED)

#灰度图像
p = img[88, 142]
print(p)

#显示图像
cv2.imshow("Demo", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()


[167 204 230]


2.RGB图像，返回R,G,B的值

例：

r = img[78,125, 2] print(r)

g = img[78, 125, 1] print(g)

b = img[78, 125, 0] print(b)



In [ ]:
b = img[78, 125, 0]
print(b)
g = img[78, 125, 1]
print(g)
r = img[78, 125, 2]
print(r)

#方法二
bgr = img[78, 125]
print(bgr)

#显示图像
cv2.imshow("Demo", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()

#写入图像
cv2.imwrite("testyxz.jpg", img)


## 2.2传统修改像素方法

1.修改单个像素值

BGR图像可以通过位置参数
直接访问像素值并进行修改


In [ ]:
print(img[78, 125, 0])
print(img[78, 125, 1])
print(img[78, 125, 2])

#修改像素
img[78, 125, 0] = 255
img[78, 125, 1] = 255
img[78, 125, 2] =255

print(img[78, 125])
img[78, 125] = [10, 10, 10]
print(img[78, 125, 0])
print(img[78, 125, 1])
print(img[78, 125, 2])


#方法二
print(img[78, 125])
img[78, 125] = [10, 10, 10]
print(img[78, 125])

2.修改区域像素

通过访问图像数组的位置区域
实现区域像素修改。

比如 [100:150,400:500] 是
访问第100到150行，
400到500列的区域，
再对该区域像素进行修改。


In [ ]:
img[100:150, 400:500] = [255, 255, 0]

#显示图像
cv2.imshow("Demo", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()

#写入图像
cv2.imwrite("testyxz.jpg", img)

## 2.3 Numpy读取像素方法

使用Numpy进行像素读取，
调用方式如下：

返回值 = 图像.item(位置参数)


In [ ]:
import cv2
import numpy

#读取图片
img = cv2.imread("test.jpg", cv2.IMREAD_UNCHANGED)

#Numpy读取像素
blue = img.item(78, 100, 0)
green = img.item(78, 100, 1)
red = img.item(78, 100, 2)
print(blue)
print(green)
print(red)

#显示图像
cv2.imshow("Demo", img)

#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()


## 2.4 Numpy 修改像素方法

使用Numpy的itemset函数修改像素，
调用方式如下：

图像.itemset(位置, 新值)
例如：

img.itemset((88,99), 255)


In [ ]:
#Numpy读取像素
print(img.item(78, 100, 0))
print(img.item(78, 100, 1))
print(img.item(78, 100, 2))
img.itemset((78, 100, 0), 100)
img.itemset((78, 100, 1), 100)
img.itemset((78, 100, 2), 100)
print(img.item(78, 100, 0))
print(img.item(78, 100, 1))
print(img.item(78, 100, 2))
#同时输出RGB 三通道方法如下
print(img[78, 78])
img.itemset((78, 78, 0), 0)
img.itemset((78, 78, 1), 0)
img.itemset((78, 78, 2), 0)
print(img[78, 78])
#[211 215 220]
#[0 0 0]